runs:
  using: "composite"
  steps:
    - name: Set up Clojure cache
      uses: actions/cache@v3
      id: clojure-cache
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn', 'bb.edn') }}
        restore-keys: |
          ${{ runner.os }}-clojure-

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
  
    - name: Set up Clojure and Babashka
      uses: DeLaGuardo/setup-clojure@0fc99a3bcdd086349bfb01a9262382fe3d37cd6d # Pinned: 12.1
      with:
        # https://clojure.org/releases/tools
        cli: '1.11.1.1429'
        # https://github.com/babashka/babashka/releases
        bb: '1.3.186'
